let dados = [
    {
        titulo: "Tiranossauro Rex",
        descricao: "Um dos maiores carnívoros terrestres que já existiu, o T-Rex era conhecido por seus poderosos dentes e mandíbulas.",
        periodo: "Periodo: Cretáceo",
        alimentacao: "Alimentação: Carnívoro",
        tamanho: "Tamanho: Até 13 metros de comprimento",
        peso: "Peso: Estima-se entre 5 e 8 toneladas",
        habitat: "Habitat: Florestas e planícies da América do Norte",
        curiosidades: "Curiosidade: O T-Rex possuía um olfato extremamente desenvolvido.",
        tags: "Carnívoro Terópode Predador Cretáceo América do Norte T rex T-Rex",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Tyrannosaurus_Rex_Skeletal.png/800px-Tyrannosaurus_Rex_Skeletal.png",
        link: "https://pt.wikipedia.org/wiki/Tiranossauro_rex"
    },
    {
        titulo: "Braquiossauro",
        descricao: "Um dos maiores animais terrestres que já viveram, o Braquiossauro era um herbívoro de pescoço longo e cauda curta.",
        periodo: "Periodo: Jurássico",
        alimentacao: "Alimentação: Herbívoro",
        tamanho: "Tamanho: Até 23 metros de altura",
        peso: "Peso: Estima-se em torno de 50 toneladas",
        habitat: "Habitat: Florestas e planícies da América do Norte",
        curiosidades: "Curiosidade: O Braquiossauro tinha um pescoço extremamente longo que lhe permitia alcançar as copas das árvores.",
        tags: "Herbívoro Saurópode Jurássico América do Norte",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Brachiosaurus_skeleton_BW.png/800px-Brachiosaurus_skeleton_BW.png",
        link: "https://pt.wikipedia.org/wiki/Braquiossauro"
    },
    {
        titulo: "Triceratops",
        descricao: "Reconhecível por seus três chifres e gola óssea, o Triceratops era um herbívoro quadrúpede.",
        periodo: "Periodo: Cretáceo",
        alimentacao: "Alimentação: Herbívoro",
        tamanho: "Tamanho: Até 9 metros de comprimento",
        peso: "Peso: Estima-se entre 6 e 12 toneladas",
        habitat: "Habitat: Planícies da América do Norte",
        curiosidades: "Curiosidade: A gola óssea do Triceratops pode ter servido para proteção ou para exibição.",
        tags: "Herbívoro Ceratopsia Cretáceo América do Norte",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Triceratops_prorsus_skull_AMNH_5027.jpg/800px-Triceratops_prorsus_skull_AMNH_5027.jpg",
        link: "https://pt.wikipedia.org/wiki/Triceratops"
    },
    {
        titulo: "Espinossauro",
        descricao: "Com uma vela nas costas e um focinho semelhante ao de um crocodilo, o Espinossauro era um predador aquático e terrestre.",
        periodo: "Periodo: Cretáceo",
        alimentacao: "Alimentação: Carnívoro",
        tamanho: "Tamanho: Até 15 metros de comprimento",
        peso: "Peso: Estima-se em torno de 7-12 toneladas",
        habitat: "Habitat: Ambientes aquáticos e terrestres da África do Norte",
        curiosidades: "Curiosidade: Acredita-se que a vela nas costas servia para regular a temperatura corporal.",
        tags: "Carnívoro Terópode Predador Cretáceo África do Norte spinosaurus",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Spinosaurus_aegyptiacus_skeleton.jpg/1280px-Spinosaurus_aegyptiacus_skeleton.jpg",
        link: "https://pt.wikipedia.org/wiki/Espinossauro"
    },
    {
        titulo: "Anquilossauro",
        descricao: "Coberto por placas ósseas e com uma clava na ponta da cauda, o Anquilossauro era uma verdadeira fortaleza.",
        periodo: "Periodo: Cretáceo",
        alimentacao: "Alimentação: Herbívoro",
        tamanho: "Tamanho: Até 10 metros de comprimento",
        peso: "Peso: Estima-se em torno de 6 toneladas",
        habitat: "Habitat: Planícies e florestas da América do Norte",
        curiosidades: "Curiosidade: Sua armadura óssea o protegia de predadores.",
        tags: "Herbívoro Anquilossauria Cretáceo América do Norte Ankylosaurus",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Ankylosaurus_magniventris_skeleton.jpg/1280px-Ankylosaurus_magniventris_skeleton.jpg",
        link: "https://pt.wikipedia.org/wiki/Anquilossauro"
    },
    {
        titulo: "Diplodoco",
        descricao: "Com um pescoço e cauda extremamente longos, o Diplodoco era um herbívoro que se alimentava das copas das árvores.",
        periodo: "Periodo: Jurássico",
        alimentacao: "Alimentação: Herbívoro",
        tamanho: "Tamanho: Até 35 metros de comprimento",
        peso: "Peso: Estima-se em torno de 20 toneladas",
        habitat: "Habitat: Florestas e planícies da América do Norte",
        curiosidades: "Curiosidade: O Diplodoco tinha uma cauda extremamente longa que pode ter sido usada para defesa.",
        tags: "Herbívoro Saurópode Jurássico América do Norte",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Diplodocus_Carnegie_skeleton.jpg/800px-Diplodocus_Carnegie_skeleton.jpg",
        link: "https://pt.wikipedia.org/wiki/Diplodoco"
    },
    {
        titulo: "Pterodáctilo",
        descricao: "Embora não fosse um dinossauro, o Pterodáctilo era um pterossauro voador que viveu na mesma época dos dinossauros.",
        periodo: "Periodo: Jurássico",
        alimentacao: "Alimentação: Carnívoro",
        tamanho: "Tamanho: Envergadura de até 2 metros",
        peso: "Peso: Estima-se em torno de 2 kg",
        habitat: "Habitat: Costas litorâneas e ilhas",
        curiosidades: "Curiosidade: O Pterodáctilo tinha uma crista na cabeça que pode ter sido usada para atrair parceiros.",
        tags: "Carnívoro Pterossauro Jurássico Voador Litorâneo",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Pterodactylus_skeleton.jpg/800px-Pterodactylus_skeleton.jpg",
        link: "https://pt.wikipedia.org/wiki/Pterodáctilo"
    },
    {
        titulo: "Iguanodonte",
        descricao: "Um dos primeiros dinossauros a ser descoberto, o Iguanodonte era um herbívoro bípede com um polegar em forma de espinho.",
        periodo: "Periodo: Cretáceo",
        alimentacao: "Alimentação: Herbívoro",
        tamanho: "Tamanho: Até 10 metros de comprimento",
        peso: "Peso: Estima-se em torno de 4 toneladas",
        habitat: "Habitat: Florestas e planícies da Europa e da América do Norte",
        curiosidades: "Curiosidade: O polegar em forma de espinho do Iguanodonte pode ter sido usado para defesa.",
        tags: "Herbívoro Ornitópoda Cretáceo Europa América do Norte",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Iguanodon_skeleton_BW.png/800px-Iguanodon_skeleton_BW.png",
        link: "https://pt.wikipedia.org/wiki/Iguanodonte"
    },
    {
        titulo: "Giganotossauro",
        descricao: "Um dos maiores carnívoros terrestres que já existiu, rivalizando em tamanho com o Tiranossauro Rex, mas com um crânio mais estreito e dentes serrilhados.",
        periodo: "Periodo: Cretáceo",
        alimentacao: "Alimentação: Carnívoro",
        tamanho: "Tamanho: Até 13 metros de comprimento",
        peso: "Peso: Estima-se entre 6 e 8 toneladas",
        habitat: "Habitat: Planícies da América do Sul",
        curiosidades: "Curiosidade: O Giganotossauro tinha um crânio maior que o do T-Rex.",
        tags: "Carnívoro Terópode Predador Cretáceo América do Sul",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Giganotosaurus_skeleton_BW.png/800px-Giganotosaurus_skeleton_BW.png",
        link: "https://pt.wikipedia.org/wiki/Giganotossauro"
    },
    {
        titulo: "Dilofossauro",
        descricao: "Famoso por sua crista óssea e a capacidade de cuspir veneno (embora essa última característica seja mais uma licença artística), o Dilofossauro era um predador relativamente pequeno.",
        periodo: "Periodo: Jurássico",
        alimentacao: "Alimentação: Carnívoro",
        tamanho: "Tamanho: Até 6 metros de comprimento",
        peso: "Peso: Estima-se em torno de 400 kg",
        habitat: "Habitat: Planícies e florestas da América do Norte",
        curiosidades: "Curiosidade: O Dilofossauro tinha uma crista óssea na cabeça que pode ter sido usada para exibição.",
        tags: "Carnívoro Terópode Predador Jurássico América do Norte",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Dilophosaurus_wetherilli_skeleton_BW.png/800px-Dilophosaurus_wetherilli_skeleton_BW.png",
        link: "https://pt.wikipedia.org/wiki/Dilofossauro"
    },
    {
        titulo: "Pachycephalosaurus",
        descricao: "Com uma grossa cúpula óssea no topo do crânio, acredita-se que o Pachycephalosaurus usasse a cabeça para embates com outros de sua espécie.",
        periodo: "Periodo: Cretáceo",
        alimentacao: "Alimentação: Herbívoro",
        tamanho: "Tamanho: Até 5 metros de comprimento",
        peso: "Peso: Estima-se em torno de 2 toneladas",
        habitat: "Habitat: Planícies da América do Norte",
        curiosidades: "Curiosidade: A cúpula óssea do Pachycephalosaurus pode ter sido usada para combates entre machos.",
        tags: "Herbívoro Pachycephalosauria Cretáceo América do Norte",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Pachycephalosaurus_skull_BW.png/800px-Pachycephalosaurus_skull_BW.png",
        link: "https://pt.wikipedia.org/wiki/Pachycephalosaurus"
    },
    {
        titulo: "Compsognato",
        descricao: "Um dos menores dinossauros conhecidos, o Compsognato era um predador ágil e rápido.",
        periodo: "Periodo: Jurássico",
        alimentacao: "Alimentação: Carnívoro",
        tamanho: "Tamanho: Até 1 metro de comprimento",
        peso: "Peso: Estima-se em torno de 3 kg",
        habitat: "Habitat: Florestas da Europa",
        curiosidades: "Curiosidade: O Compsognato tinha um corpo leve e ossos ocos, o que o tornava um corredor rápido.",
        tags: "Carnívoro Terópode Predador Jurássico Europa",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Compsognathus_skeleton_BW.png/800px-Compsognathus_skeleton_BW.png",
        link: "https://pt.wikipedia.org/wiki/Compsognato"
    },
    {
        titulo: "Gallimimus",
        descricao: "Com aparência semelhante a um avestruz, o Gallimimus era um ornitomímido que corria rapidamente e se alimentava de plantas.",
        periodo: "Periodo: Cretáceo",
        alimentacao: "Alimentação: Omnívoro",
        tamanho: "Tamanho: Até 6 metros de comprimento",
        peso: "Peso: Estima-se em torno de 450 kg",
        habitat: "Habitat: Planícies da Mongólia",
        curiosidades: "Curiosidade: O Gallimimus tinha um bico longo e estreito que lhe permitia comer pequenas pedras para auxiliar na digestão.",
        tags: "Omnívoro Ornitomímido Cretáceo Mongólia",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Gallimimus_skeleton.jpg/800px-Gallimimus_skeleton.jpg",
        link: "https://pt.wikipedia.org/wiki/Gallimimus"
    },
    {
        titulo: "Alossauro",
        descricao: "Um dos maiores predadores do Jurássico, conhecido por seus dentes afiados e braços poderosos.",
        periodo: "Periodo: Jurássico",
        alimentacao: "Alimentação: Carnívoro",
        tamanho: "Tamanho: Até 12 metros de comprimento",
        peso: "Peso: Até 2 toneladas",
        habitat: "Habitat: Florestas e planícies da América do Norte",
        curiosidades: "Curiosidade: Seus braços eram relativamente longos em comparação com outros grandes terópodes.",
        tags: "Carnívoro Terópode Predador Jurássico América do Norte",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Allosaurus_BW.png/800px-Allosaurus_BW.png",
        link: "https://pt.wikipedia.org/wiki/Allosaurus"
    },
    {
        titulo: "Velociraptor",
        descricao: "Menor que muitos outros dinossauros, o Velociraptor era um predador ágil e inteligente.",
        periodo: "Periodo: Cretáceo",
        alimentacao: "Alimentação: Carnívoro",
        tamanho: "Tamanho: Até 2 metros de comprimento",
        peso: "Peso: Estima-se em torno de 15 kg",
        habitat: "Habitat: Desertos da Ásia Central",
        curiosidades: "Curiosidade: O Velociraptor tinha garras grandes e curvadas nos pés que usava para caçar.",
        tags: "Carnívoro Terópode Predador Cretáceo Ásia Central",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Velociraptor_skeleton.jpg/800px-Velociraptor_skeleton.jpg",
        link: "https://pt.wikipedia.org/wiki/Velociraptor"
    },
    {
        titulo: "Estegossauro",
        descricao: "Conhecido por suas placas ósseas nas costas e espinhos na cauda, o Estegossauro era um herbívoro quadrúpede.",
        periodo: "Periodo: Jurássico",
        alimentacao: "Alimentação: Herbívoro",
        tamanho: "Tamanho: Até 9 metros de comprimento",
        peso: "Peso: Estima-se em torno de 3 toneladas",
        habitat: "Habitat: Florestas e planícies da América do Norte",
        curiosidades: "Curiosidade: As placas ósseas do Estegossauro podem ter sido usadas para regulação térmica ou para exibição.",
        tags: "Herbívoro Estegossauria Jurássico América do Norte",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Stegosaurus_skeleton_BW.png/800px-Stegosaurus_skeleton_BW.png",
        link: "https://pt.wikipedia.org/wiki/Estegossauro"
    },
    {
        titulo: "Pteranodonte",
        descricao: "Embora não fosse um dinossauro, o Pteranodonte era um pterossauro, um réptil voador que viveu na mesma época dos dinossauros.",
        periodo: "Periodo: Cretáceo",
        alimentacao: "Alimentação: Carnívoro",
        tamanho: "Tamanho: Envergadura de até 7 metros",
        peso: "Peso: Estima-se em torno de 20 kg",
        habitat: "Habitat: Costas litorâneas da América do Norte",
        curiosidades: "Curiosidade: O Pteranodonte tinha uma crista óssea na cabeça que pode ter sido usada para estabilidade durante o voo.",
        tags: "Carnívoro Pterossauro Cretáceo Voador Litorâneo",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Pteranodon_longiceps_skeleton_BW.png/800px-Pteranodon_longiceps_skeleton_BW.png",
        link: "https://pt.wikipedia.org/wiki/Pteranodon"
    },
    {
        titulo: "Archaeopterix",
        descricao: "Uma criatura que apresentava características de répteis e aves, o Archaeopterix é considerado um elo evolutivo importante.",
        periodo: "Periodo: Jurássico Superior",
        alimentacao: "Alimentação: Carnívoro",
        tamanho: "Tamanho: Cerca de 50 cm de comprimento",
        peso: "Peso: Estima-se em torno de 0,5 kg",
        habitat: "Habitat: Florestas da Alemanha",
        curiosidades: "Curiosidade: Possuía penas, mas também garras nas asas e uma longa cauda óssea.",
        tags: "Carnívoro Ave Primitiva Jurássico Alemanha",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Archaeopteryx_skeleton_BW.png/800px-Archaeopteryx_skeleton_BW.png",
        link: "https://pt.wikipedia.org/wiki/Archaeopteryx"
    },
    {
        titulo: "Camptossauro",
        descricao: "Um dinossauro herbívoro bípede, o Camptossauro era conhecido por seus dentes afiados e seu crânio peculiar.",
        periodo: "Periodo: Jurássico Superior",
        alimentacao: "Alimentação: Herbívoro",
        tamanho: "Tamanho: Até 6 metros de comprimento",
        peso: "Peso: Estima-se em torno de 1 tonelada",
        habitat: "Habitat: Florestas e planícies da América do Norte",
        curiosidades: "Curiosidade: O Camptossauro tinha um crânio com uma ponta arredondada e um bico estreito.",
        tags: "Herbívoro Ornitópoda Jurássico América do Norte",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Camptosaurus_skeleton.jpg/800px-Camptosaurus_skeleton.jpg",
        link: "https://pt.wikipedia.org/wiki/Camptossauro"
    },
    {
        titulo: "Apatossauro",
        descricao: "Um dos maiores dinossauros que já existiu, o Apatossauro era um herbívoro de pescoço longo e cauda longa.",
        periodo: "Periodo: Jurássico Superior",
        alimentacao: "Alimentação: Herbívoro",
        tamanho: "Tamanho: Até 26 metros de comprimento",
        peso: "Peso: Estima-se em torno de 22 toneladas",
        habitat: "Habitat: Florestas e planícies da América do Norte",
        curiosidades: "Curiosidade: O Apatossauro tinha um pescoço longo e flexível que lhe permitia alcançar as copas das árvores.",
        tags: "Herbívoro Saurópode Jurássico América do Norte",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Apatosaurus_skeleton.jpg/800px-Apatosaurus_skeleton.jpg",
        link: "https://pt.wikipedia.org/wiki/Apatossauro"
    },
    {
        titulo: "Maiassaura",
        descricao: "Conhecido por seus cuidados parentais excepcionais, a Maiassaura era um herbívoro que vivia em bandos.",
        periodo: "Periodo: Cretáceo Inferior",
        alimentacao: "Alimentação: Herbívoro",
        tamanho: "Tamanho: Até 9 metros de comprimento",
        peso: "Peso: Estima-se em torno de 3 toneladas",
        habitat: "Habitat: Planícies da América do Norte",
        curiosidades: "Curiosidade: Os ninhos da Maiassaura eram encontrados em grandes grupos, indicando que eles viviam em bandos e cuidavam de seus filhotes em conjunto.",
        tags: "Herbívoro Hadrossauridae Cretáceo América do Norte",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Maiasaura_peeblesorum_skeleton.jpg/800px-Maiasaura_peeblesorum_skeleton.jpg",
        link: "https://pt.wikipedia.org/wiki/Maiassaura"
    },
    {
        titulo: "Parasaurolophus",
        descricao: "Famoso por sua crista óssea em forma de tubo na cabeça, o Parasaurolophus era um herbívoro que usava a crista para comunicação.",
        periodo: "Periodo: Cretáceo Superior",
        alimentacao: "Alimentação: Herbívoro",
        tamanho: "Tamanho: Até 10 metros de comprimento",
        peso: "Peso: Estima-se em torno de 2 toneladas",
        habitat: "Habitat: Planícies da América do Norte",
        curiosidades: "Curiosidade: A crista do Parasaurolophus provavelmente servia para amplificar sons e produzir um chamado alto para comunicação.",
        tags: "Herbívoro Hadrossauridae Cretáceo América do Norte",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Parasaurolophus_walkeri_skeleton.jpg/800px-Parasaurolophus_walkeri_skeleton.jpg",
        link: "https://pt.wikipedia.org/wiki/Parasaurolophus"
    },
    {
        titulo: "Corythosaurus",
        descricao: "Com uma crista óssea na cabeça semelhante à de um capacete, o Corythosaurus era um herbívoro que se alimentava de plantas.",
        periodo: "Periodo: Cretáceo Superior",
        alimentacao: "Alimentação: Herbívoro",
        tamanho: "Tamanho: Até 9 metros de comprimento",
        peso: "Peso: Estima-se em torno de 3 toneladas",
        habitat: "Habitat: Planícies da América do Norte",
        curiosidades: "Curiosidade: A crista do Corythosaurus provavelmente servia para comunicação e exibição.",
        tags: "Herbívoro Hadrossauridae Cretáceo América do Norte",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Corythosaurus_skull.jpg/800px-Corythosaurus_skull.jpg",
        link: "https://pt.wikipedia.org/wiki/Corythosaurus"
    },
    {
        titulo: "Iguanodon",
        descricao: "Um dos primeiros dinossauros a ser descoberto, o Iguanodon era um herbívoro bípede com um polegar em forma de espinho.",
        periodo: "Periodo: Cretáceo",
        alimentacao: "Alimentação: Herbívoro",
        tamanho: "Tamanho: Até 10 metros de comprimento",
        peso: "Peso: Estima-se em torno de 4 toneladas",
        habitat: "Habitat: Florestas e planícies da Europa e da América do Norte",
        curiosidades: "Curiosidade: O polegar em forma de espinho do Iguanodonte pode ter sido usado para defesa.",
        tags: "Herbívoro Ornitópoda Cretáceo Europa América do Norte",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Iguanodon_skeleton_BW.png/800px-Iguanodon_skeleton_BW.png",
        link: "https://pt.wikipedia.org/wiki/Iguanodonte"
    },
    {
        titulo: "Carnotauro",
        descricao: "Um carnívoro com chifres curtos acima dos olhos, o Carnotauro era um predador veloz e agressivo.",
        periodo: "Periodo: Cretáceo Superior",
        alimentacao: "Alimentação: Carnívoro",
        tamanho: "Tamanho: Até 9 metros de comprimento",
        peso: "Peso: Estima-se em torno de 1,5 toneladas",
        habitat: "Habitat: Planícies da América do Sul",
        curiosidades: "Curiosidade: Os braços do Carnotauro eram extremamente pequenos, quase vestigiais.",
        tags: "Carnívoro Terópode Predador Cretáceo América do Sul",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Carnotaurus_skeleton.jpg/800px-Carnotaurus_skeleton.jpg",
        link: "https://pt.wikipedia.org/wiki/Carnotauro"
    },
    {
        titulo: "Ceratossauro",
        descricao: "Um dinossauro carnívoro com um chifre no nariz, o Ceratossauro era um predador que vivia em grupos.",
        periodo: "Periodo: Jurássico Superior",
        alimentacao: "Alimentação: Carnívoro",
        tamanho: "Tamanho: Até 6 metros de comprimento",
        peso: "Peso: Estima-se em torno de 1 tonelada",
        habitat: "Habitat: Florestas e planícies da América do Norte",
        curiosidades: "Curiosidade: O Ceratossauro tinha um crânio robusto com um único chifre no nariz.",
        tags: "Carnívoro Terópode Predador Jurássico América do Norte",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Ceratosaurus_nasicornis_skeleton_BW.png/800px-Ceratosaurus_nasicornis_skeleton_BW.png",
        link: "https://pt.wikipedia.org/wiki/Ceratossauro"
    },
    {
        titulo: "Baryonyx",
        descricao: "Um dinossauro carnívoro com garras enormes nas mãos, o Baryonyx era um predador especializado em peixes.",
        periodo: "Periodo: Cretáceo Inferior",
        alimentacao: "Alimentação: Carnívoro",
        tamanho: "Tamanho: Até 10 metros de comprimento",
        peso: "Peso: Estima-se em torno de 2 toneladas",
        habitat: "Habitat: Ambientes aquáticos da Europa",
        curiosidades: "Curiosidade: O Baryonyx tinha garras grandes e curvadas nas mãos, perfeitas para capturar peixes.",
        tags: "Carnívoro Terópode Predador Cretáceo Europa",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Baryonyx_skeleton.jpg/800px-Baryonyx_skeleton.jpg",
        link: "https://pt.wikipedia.org/wiki/Baryonyx"
    },
    {
        titulo: "Compsognato",
        descricao: "Um dos menores dinossauros conhecidos, o Compsognato era um predador ágil e rápido.",
        periodo: "Periodo: Jurássico",
        alimentacao: "Alimentação: Carnívoro",
        tamanho: "Tamanho: Até 1 metro de comprimento",
        peso: "Peso: Estima-se em torno de 3 kg",
        habitat: "Habitat: Florestas da Europa",
        curiosidades: "Curiosidade: O Compsognato tinha um corpo leve e ossos ocos, o que o tornava um corredor rápido.",
        tags: "Carnívoro Terópode Predador Jurássico Europa",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Compsognathus_skeleton_BW.png/800px-Compsognathus_skeleton_BW.png",
        link: "https://pt.wikipedia.org/wiki/Compsognato"
    },
    {
        titulo: "Carcharodontossauro",
        descricao: "Um grande carnívoro com dentes semelhantes aos de um tubarão, o Carcharodontossauro era um predador que competia com o Espinossauro.",
        periodo: "Periodo: Cretáceo Inferior",
        alimentacao: "Alimentação: Carnívoro",
        tamanho: "Tamanho: Até 13 metros de comprimento",
        peso: "Peso: Estima-se em torno de 6 toneladas",
        habitat: "Habitat: Desertos da África do Norte",
        curiosidades: "Curiosidade: O Carcharodontossauro tinha dentes muito afiados e serrilhados, ideais para cortar carne.",
        tags: "Carnívoro Terópode Predador Cretáceo África do Norte",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Carcharodontosaurus_skeleton.jpg/800px-Carcharodontosaurus_skeleton.jpg",
        link: "https://pt.wikipedia.org/wiki/Carcharodontossauro"
    },
    {
        titulo: "Ornitomimo",
        descricao: "Com aparência semelhante a um avestruz, o Ornitomimo era um dinossauro veloz e ágil que se alimentava de plantas.",
        periodo: "Periodo: Cretáceo Superior",
        alimentacao: "Alimentação: Omnívoro",
        tamanho: "Tamanho: Até 4 metros de comprimento",
        peso: "Peso: Estima-se em torno de 300 kg",
        habitat: "Habitat: Planícies da América do Norte",
        curiosidades: "Curiosidade: O Ornitomimo tinha pernas longas e braços curtos, o que lhe permitia correr rapidamente.",
        tags: "Omnívoro Ornitomímido Cretáceo América do Norte",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Ornithomimus_skeleton_BW.png/800px-Ornithomimus_skeleton_BW.png",
        link: "https://pt.wikipedia.org/wiki/Ornitomimo"
    },
    {
        titulo: "Amargasaurus",
        descricao: "Um dinossauro herbívoro com duas fileiras de espinhos ósseos nas costas, o Amargasaurus era um animal único.",
        periodo: "Periodo: Jurássico Superior",
        alimentacao: "Alimentação: Herbívoro",
        tamanho: "Tamanho: Até 10 metros de comprimento",
        peso: "Peso: Estima-se em torno de 3 toneladas",
        habitat: "Habitat: Florestas da América do Sul",
        curiosidades: "Curiosidade: Os espinhos do Amargasaurus podem ter servido para exibição, defesa ou para regular a temperatura corporal.",
        tags: "Herbívoro Saurópode Jurássico América do Sul",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Amargasaurus_skeleton.jpg/800px-Amargasaurus_skeleton.jpg",
        link: "https://pt.wikipedia.org/wiki/Amargasaurus"
    }
];